### PR TITLE
Add Verified Indication

### PR DESCRIPTION
**Pull request by danlee1025**
Checks JWS signature and adds verified indication on file upload and QR code scan.

3 images of the possible cases below:
image
image
image

### CODE REVIEW

**Comment by radamson** [comment]
I haven't checked yet to confirm if this happens on master too, but if I try to click the `Upload` button before selecting a file I see:

Screen Shot 2021-05-17 at 2 06 22 PM

It would be nice if the upload button was disabled until a file was selected (or do we even need both buttons?)

**Comment by radamson** [comment]
Also I tried with the file upload and didn't see the verification icon with the file upload
Screen Shot 2021-05-17 at 2 10 12 PM

**Comment by radamson** [comment]
So @danlee1025 counseled me to do a `bundle install` after which the verification status started showing up when verifying.

Here's a couple examples illustrating the expected errors (tested to make sure it'd work)

Screen Shot 2021-05-17 at 2 30 38 PM
Screen Shot 2021-05-17 at 2 28 53 PM

**Review by radamson — APPROVED** [review]
Code looks good and testing it out everything worked.

It would be nice to add a couple tests for `HealthCards::Importer` at some point.

**Comment by pmadria** [comment]
Code functionality works as intended for both uploading and scanning

**Review by radamson — APPROVED** [review]
Double approved.

**Pull request merged**
